#
# Module manifest for module 'Home-Assistant'
#
# Generated by: Flemming Sørvollen Skaret
#
# Generated on: 11.06.2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Home-Assistant.psm1'

# ModuleVersion ignore this, but this is required
ModuleVersion = '0.0.0'

# ID used to uniquely identify this module
GUID = '9bfaf5c0-e44e-4715-b7f3-1cbc68713f6e'

# Author of this module
Author = 'Flemming Sørvollen Skaret'

# Copyright statement for this module
Copyright = '(c) 2019 Flemming Sørvollen Skaret.'

# Description of the functionality provided by this module
Description = 'A PowerShell Module to Control the Home-Assistant home automation software'

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/flemmingss/Home-Assistant-PowerShell-Module'

}
